jokes = ["Saryn. Want some STD?",
         "Mesa. Ya'll bow down to the cowgirl.",
         "Mag. Plenty of things she can pull.",
         "Volt. Doing it fast and clean.",
         "Ash. Thrust, thrust, thrust your blade...",
         "Loki. Always good and prepared for every occasion.",
         "Rhino. Protection first, charging later.",
         "Chroma. THIS IS A STRICTLY SCALIE HOUSEHOLD.",
         "Valkyr. Ropes, whips, and claws have never been THIS FUN.",
         "Oberon. Everybody gets some of him.",
         "Frost. Don't mind your frozen balls. Just chill.",
         "Vauban. Throws balls around. What else is there to say?",
         "Trinity. A dish best eaten from inbetween.",
         "Nyx. Domination at its finest.",
         "Excalibur. Starting out strong, last one to finish.",
         "Inaros. POCKET SAND.",
         "Equinox. Can't love yourself better than this.",
         "Atlas. Prepare for some fistin'.",
         "Nova. Prepare your body to be basted by explosions.",
         "Wukong. WHY WON'T YOU FINISH?!",
         "Nezha. Not to be confused with Hatsune Miku.",
         "Ivara. Tugging on your hips with these dashwires.",
         "Opticor, Lanka, Snipetron, Punchthrough. Maximum penetration.",
         "Phage. Several strokes and your ultimate weapon's ready to go again.",
         "Braton. A first timer's best friend.",
         "Vectis. Top quality wood.",
         "Grakata. You just need to let out more money shots!",
         "Atterax. If normal punching and contact just isn't your type.",
         "Prova. Compensation's always an option.",
         "Kohm. Don't tell me you didn't read that one a different way. I know.",
         "Stug. Every lady would want some of those blobs of life.",
         "Prime Gear. Technically normal. They just got the golden shower.",
         "Boltor. Perfect for an alternative on 'nailing'."]